import { Resend } from 'resend'

let _resend: Resend | null = null
const resend = () => {
  if (!_resend) _resend = new Resend(process.env.RESEND_API_KEY!)
  return _resend
}

const FROM_EMAIL = 'PersonaLink <noreply@personalink.in>'
const APP_URL = process.env.NEXT_PUBLIC_APP_URL!

export async function sendApprovalEmail({
  to,
  userName,
  postContent,
  approvalToken,
  scheduledAt,
}: {
  to: string
  userName: string
  postContent: string
  approvalToken: string
  scheduledAt?: string | null
}) {
  const approveUrl = `${APP_URL}/approve/${approvalToken}?action=approve`
  const rejectUrl = `${APP_URL}/approve/${approvalToken}?action=reject`

  const scheduleLabel = scheduledAt
    ? new Date(scheduledAt).toLocaleString('en-IN', {
        weekday: 'long', day: 'numeric', month: 'long',
        hour: '2-digit', minute: '2-digit', hour12: true,
        timeZone: 'Asia/Kolkata',
      })
    : null

  const scheduleBanner = scheduleLabel
    ? `<div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;padding:14px 16px;margin-bottom:24px;display:flex;align-items:center;gap:12px;">
        <span style="font-size:18px;">📅</span>
        <div>
          <p style="margin:0;font-size:13px;font-weight:600;color:#1e40af;">Scheduled to post on</p>
          <p style="margin:0;font-size:14px;color:#1d4ed8;">${scheduleLabel} IST</p>
        </div>
      </div>`
    : ''

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: scheduleLabel
      ? `Approve your LinkedIn post — going live ${scheduleLabel} IST`
      : `Your LinkedIn post is ready for approval`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <img src="${APP_URL}/logo-text.png" alt="PersonaLink" style="height:28px;width:auto;display:block;" />
        </div>
      </div>
    </div>

    <div style="padding:32px;">
      <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#0f172a;">Your post is ready, ${userName.split(' ')[0]}!</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:15px;">Review your AI-generated LinkedIn post below and approve or reject it.</p>

      ${scheduleBanner}

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:28px;">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:14px;">
          <div style="width:8px;height:8px;background:#0A66C2;border-radius:50%;"></div>
          <span style="font-size:12px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">LinkedIn Post Preview</span>
        </div>
        <p style="margin:0;color:#0f172a;font-size:15px;line-height:1.7;white-space:pre-wrap;">${postContent}</p>
      </div>

      <div style="display:flex;gap:12px;margin-bottom:24px;">
        <a href="${approveUrl}" style="flex:1;display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;">
          Approve &amp; Post
        </a>
        <a href="${rejectUrl}" style="flex:1;display:block;text-align:center;background:white;color:#64748b;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;border:1px solid #e2e8f0;">
          Reject
        </a>
      </div>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        This post was generated by PersonaLink AI. You can always edit it in your
        <a href="${APP_URL}/dashboard/posts" style="color:#0A66C2;">dashboard</a>.
      </p>
    </div>
  </div>
</body>
</html>
    `,
    text: `Your LinkedIn post is ready for approval!${scheduleLabel ? `\n\nScheduled: ${scheduleLabel} IST` : ''}\n\n${postContent}\n\nApprove: ${approveUrl}\nReject: ${rejectUrl}`,
  })
}

export async function sendWeeklyDigestEmail({
  to,
  userName,
  trendingTopics,
  postInsight,
  scheduledCount,
}: {
  to: string
  userName: string
  trendingTopics: Array<{ title: string; angle: string }>
  postInsight: string
  scheduledCount: number
}) {
  const firstName = userName.split(' ')[0]
  const topicsHtml = trendingTopics
    .map(
      (t, i) => `
    <div style="border-left:3px solid #0A66C2;padding:12px 16px;margin-bottom:12px;background:#f8fafc;border-radius:0 8px 8px 0;">
      <p style="margin:0 0 4px;font-weight:600;color:#0f172a;font-size:14px;">${i + 1}. ${t.title}</p>
      <p style="margin:0;color:#64748b;font-size:13px;">${t.angle}</p>
    </div>`
    )
    .join('')

  const scheduleNote =
    scheduledCount < 3
      ? `<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:8px;padding:14px 16px;margin-bottom:24px;">
          <p style="margin:0;font-size:13px;color:#92400e;">You have <strong>${scheduledCount} post${scheduledCount !== 1 ? 's' : ''}</strong> scheduled this week. Aim for at least 3 for consistent growth.</p>
        </div>`
      : ''

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Your LinkedIn content ideas for this week, ${firstName}`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <img src="${APP_URL}/logo-text.png" alt="PersonaLink" style="height:28px;width:auto;display:block;" />
        </div>
      </div>
      <p style="margin:16px 0 0;color:rgba(255,255,255,0.85);font-size:14px;">Your weekly content briefing</p>
    </div>

    <div style="padding:32px;">
      <h1 style="margin:0 0 6px;font-size:20px;font-weight:600;color:#0f172a;">Good morning, ${firstName}!</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:14px;">Here are 3 trending topics to post about this week.</p>

      ${scheduleNote}

      <h2 style="margin:0 0 14px;font-size:15px;font-weight:600;color:#0f172a;">Trending in your industry</h2>
      ${topicsHtml}

      <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:14px 16px;margin:24px 0;">
        <p style="margin:0 0 4px;font-size:12px;font-weight:600;color:#166534;text-transform:uppercase;letter-spacing:0.05em;">Your insight</p>
        <p style="margin:0;color:#15803d;font-size:14px;">${postInsight}</p>
      </div>

      <a href="${APP_URL}/dashboard/suggestions" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:16px;">
        See all suggestions →
      </a>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        Sent every Monday by <a href="${APP_URL}/dashboard" style="color:#0A66C2;">PersonaLink</a>.
        Your topics are refreshed every 6 hours.
      </p>
    </div>
  </div>
</body>
</html>`,
    text: `Your LinkedIn content ideas for this week\n\n${trendingTopics.map((t, i) => `${i + 1}. ${t.title}\n   ${t.angle}`).join('\n\n')}\n\n${postInsight}\n\nSee all suggestions: ${APP_URL}/dashboard/suggestions`,
  })
}

export async function sendImageBriefEmail({
  to,
  userName,
  prompts,
  month,
}: {
  to: string
  userName: string
  prompts: string[]
  month: string
}) {
  const firstName = userName.split(' ')[0]
  const promptsHtml = prompts
    .map((p, i) => `
    <div style="display:flex;gap:14px;padding:14px 0;border-bottom:1px solid #f1f5f9;align-items:flex-start;">
      <div style="width:28px;height:28px;background:#e8f0fb;border-radius:8px;display:flex;align-items:center;justify-content:center;font-weight:700;color:#0A66C2;font-size:13px;flex-shrink:0;">${i + 1}</div>
      <p style="margin:0;color:#374151;font-size:14px;line-height:1.6;">${p}</p>
    </div>`)
    .join('')

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Your LinkedIn photo brief for ${month}, ${firstName}`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <img src="${APP_URL}/logo-text.png" alt="PersonaLink" style="height:28px;width:auto;display:block;" />
        </div>
      </div>
    </div>
    <div style="padding:32px;">
      <h1 style="margin:0 0 8px;font-size:20px;font-weight:700;color:#0f172a;">Your photo brief for ${month}</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:14px;">
        5 specific photos to shoot this month. Images boost LinkedIn engagement by up to 3×.
      </p>
      <div>${promptsHtml}</div>
      <div style="margin-top:24px;background:#fffbeb;border:1px solid #fcd34d;border-radius:10px;padding:14px 16px;">
        <p style="margin:0;font-size:13px;color:#92400e;">
          💡 Batch-shoot these in one session. Natural light, candid moments, real settings — not stock photo vibes.
        </p>
      </div>
      <a href="${APP_URL}/dashboard" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-top:24px;">
        Open Dashboard →
      </a>
    </div>
  </div>
</body>
</html>`,
    text: `Your LinkedIn photo brief for ${month}\n\n${prompts.map((p, i) => `${i + 1}. ${p}`).join('\n\n')}\n\n${APP_URL}/dashboard`,
  })
}

export async function sendWelcomeEmail({
  to,
  userName,
}: {
  to: string
  userName: string
}) {
  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Welcome to PersonaLink, ${userName.split(' ')[0]}!`,
    html: `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;padding:40px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <h1 style="color:#0f172a;font-size:22px;margin-bottom:16px;">Welcome aboard, ${userName.split(' ')[0]}!</h1>
    <p style="color:#374151;line-height:1.7;">Your LinkedIn account is connected. Here's how to get started:</p>
    <ol style="color:#374151;line-height:2;">
      <li>Set up your <a href="${APP_URL}/onboarding" style="color:#0A66C2;">content profile</a> — your role, topics, and writing style</li>
      <li>Generate your first post with AI</li>
      <li>Approve it via email or directly on the dashboard</li>
      <li>Schedule it to go live at the perfect time</li>
    </ol>
    <a href="${APP_URL}/onboarding" style="display:inline-block;margin-top:16px;background:#0A66C2;color:white;text-decoration:none;padding:14px 28px;border-radius:8px;font-weight:600;">Complete setup →</a>
  </div>
</body>
</html>
    `,
    text: `Welcome to PersonaLink, ${userName.split(' ')[0]}! Complete your setup: ${APP_URL}/onboarding`,
  })
}

export async function sendTrialStartedEmail({
  to,
  userName,
  trialEndsAt,
  plan,
}: {
  to: string
  userName: string
  trialEndsAt: Date
  plan: string
}) {
  const firstName = userName.split(' ')[0]
  const endsDate = trialEndsAt.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
  const planAmounts: Record<string, string> = { starter: '₹999', standard: '₹2,500', pro: '₹5,000' }
  const amount = planAmounts[plan] || '₹999'
  const planLabel = plan.charAt(0).toUpperCase() + plan.slice(1)

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: `Your 7-day free trial has started, ${firstName}!`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <img src="${APP_URL}/logo-text.png" alt="PersonaLink" style="height:28px;width:auto;display:block;" />
        </div>
      </div>
    </div>

    <div style="padding:32px;">
      <div style="background:#ecfdf5;border:1px solid #bbf7d0;border-radius:12px;padding:16px 20px;margin-bottom:24px;display:flex;align-items:center;gap:12px;">
        <div style="width:32px;height:32px;background:#059669;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;">
          <span style="color:white;font-size:16px;">✓</span>
        </div>
        <div>
          <p style="margin:0;font-weight:600;color:#065f46;font-size:14px;">7-day free trial activated</p>
          <p style="margin:0;color:#047857;font-size:13px;">You won't be charged until ${endsDate}</p>
        </div>
      </div>

      <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#0f172a;">Your trial has started, ${firstName}!</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:15px;">You have full access to the <strong>${planLabel}</strong> plan for the next 7 days — completely free.</p>

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:28px;">
        <h2 style="margin:0 0 14px;font-size:14px;font-weight:600;color:#0f172a;">Trial details</h2>
        <table style="width:100%;border-collapse:collapse;">
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Plan</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${planLabel}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Trial ends</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${endsDate}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">First charge</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${amount}/mo on ${endsDate}</td>
          </tr>
        </table>
      </div>

      <p style="margin:0 0 20px;color:#64748b;font-size:14px;">Get started by generating your first LinkedIn post.</p>

      <a href="${APP_URL}/dashboard" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:16px;">
        Go to Dashboard →
      </a>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        You can cancel anytime before ${endsDate} — no charge.
        <a href="${APP_URL}/dashboard/settings?tab=plan" style="color:#0A66C2;">Manage subscription</a>
      </p>
    </div>
  </div>
</body>
</html>`,
    text: `Your 7-day free trial has started!\n\nPlan: ${planLabel}\nTrial ends: ${endsDate}\nFirst charge: ${amount}/mo on ${endsDate}\n\nYou have full access for 7 days. No charge until ${endsDate}.\n\nGo to dashboard: ${APP_URL}/dashboard`,
  })
}


export async function sendPipelineReminderEmail({
  to,
  userName,
  upcomingCount,
  postsUsed,
  postsLimit,
  plan,
}: {
  to: string
  userName: string
  upcomingCount: number
  postsUsed: number
  postsLimit: number
  plan: string
}) {
  const firstName = userName.split(' ')[0]
  const remaining = postsLimit - postsUsed
  const planLabel = plan.charAt(0).toUpperCase() + plan.slice(1)

  const urgencyColor = upcomingCount === 0 ? '#dc2626' : '#d97706'
  const urgencyBg = upcomingCount === 0 ? '#fef2f2' : '#fffbeb'
  const urgencyBorder = upcomingCount === 0 ? '#fca5a5' : '#fcd34d'
  const pipelineMessage =
    upcomingCount === 0
      ? `You have <strong>no posts scheduled</strong> — your LinkedIn presence will go quiet soon.`
      : `You only have <strong>${upcomingCount} post${upcomingCount !== 1 ? 's' : ''} left</strong> in your queue.`

  return resend().emails.send({
    from: FROM_EMAIL,
    to,
    subject: upcomingCount === 0
      ? `Your LinkedIn queue is empty, ${firstName} — time to refill it`
      : `Your post queue is running low, ${firstName}`,
    html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">

    <div style="background:#0A66C2;padding:28px 32px;">
      <div>
        <div style="background:white;border-radius:8px;padding:6px 12px;display:inline-block;">
          <img src="${APP_URL}/logo-text.png" alt="PersonaLink" style="height:28px;width:auto;display:block;" />
        </div>
      </div>
    </div>

    <div style="padding:32px;">
      <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#0f172a;">Keep the momentum going, ${firstName}</h1>
      <p style="margin:0 0 24px;color:#64748b;font-size:15px;">Consistent posting is what drives LinkedIn growth — here's a quick check-in on your queue.</p>

      <div style="background:${urgencyBg};border:1px solid ${urgencyBorder};border-radius:10px;padding:16px 18px;margin-bottom:24px;">
        <p style="margin:0;font-size:14px;color:${urgencyColor};">${pipelineMessage}</p>
      </div>

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:20px;margin-bottom:28px;">
        <h2 style="margin:0 0 14px;font-size:14px;font-weight:600;color:#0f172a;">Your ${planLabel} plan this month</h2>
        <table style="width:100%;border-collapse:collapse;">
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Posts generated</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:#0f172a;font-size:14px;">${postsUsed} / ${postsLimit}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Generations remaining</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:${remaining > 5 ? '#059669' : '#d97706'};font-size:14px;">${remaining}</td>
          </tr>
          <tr>
            <td style="padding:6px 0;color:#64748b;font-size:14px;">Posts in queue</td>
            <td style="padding:6px 0;text-align:right;font-weight:600;color:${upcomingCount > 0 ? '#0f172a' : '#dc2626'};font-size:14px;">${upcomingCount}</td>
          </tr>
        </table>
      </div>

      <a href="${APP_URL}/dashboard" style="display:block;text-align:center;background:#0A66C2;color:white;text-decoration:none;padding:14px 20px;border-radius:8px;font-weight:600;font-size:15px;margin-bottom:16px;">
        Generate posts now →
      </a>

      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        You're on the ${planLabel} plan. Resets on the 1st of each month.<br>
        <a href="${APP_URL}/dashboard/settings?tab=plan" style="color:#0A66C2;">Manage subscription</a>
      </p>
    </div>
  </div>
</body>
</html>`,
    text: `Keep the momentum going, ${firstName}!\n\n${upcomingCount === 0 ? 'Your LinkedIn queue is empty.' : `You have ${upcomingCount} post${upcomingCount !== 1 ? 's' : ''} left in your queue.`}\n\nThis month: ${postsUsed}/${postsLimit} posts generated, ${remaining} remaining.\n\nGenerate posts now: ${APP_URL}/dashboard`,
  })
}

export async function sendAdminAlert({ subject, body }: { subject: string; body: string }) {
  const adminEmail = process.env.ADMIN_EMAIL || 'hamzabamboat@gmail.com'
  return resend().emails.send({
    from: FROM_EMAIL,
    to: adminEmail,
    subject,
    html: `<div style="font-family:monospace;white-space:pre-wrap;padding:24px;background:#f8fafc;border-radius:8px;">${body}</div>`,
    text: body,
  })
}
